name = "vite-react-template"
account_id = "06740579813f72fcc4dce70ee7eed272"
workers_dev = true

# Specify the directory where Vite builds your project
pages_build_output_dir = "dist"

# Define the build command
[build]
command = "npm run build"
