/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cafe.gltf 
Author: anarki3000 (https://sketchfab.com/anarki3000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-shop-cb6fde1b9baa4cde9a5d99490cced7a0
Title: Coffee Shop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3Dmodels/Cafe/cafe.gltf')
  return (
    <group {...props} dispose={null} scale={0.7}>
      <group rotation={[-Math.PI / 2, -0.005, -1.6]}>
        <group position={[-40, -40, -30]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.VoxMaterial_24} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.VoxMaterial_36} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.VoxMaterial_37} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.VoxMaterial_39} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.VoxMaterial_40} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.VoxMaterial_47} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.VoxMaterial_48} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.VoxMaterial_56} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.VoxMaterial_64} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.VoxMaterial_71} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.VoxMaterial_78} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.VoxMaterial_80} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.VoxMaterial_88} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.VoxMaterial_96} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.VoxMaterial_103} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.VoxMaterial_104} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.VoxMaterial_120} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.VoxMaterial_136} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.VoxMaterial_147} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.VoxMaterial_148} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.VoxMaterial_149} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.VoxMaterial_150} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.VoxMaterial_151} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.VoxMaterial_152} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.VoxMaterial_174} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.VoxMaterial_175} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.VoxMaterial_176} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.VoxMaterial_182} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.VoxMaterial_183} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.VoxMaterial_184} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.VoxMaterial_199} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.VoxMaterial_200} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.VoxMaterial_216} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.VoxMaterial_232} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.VoxMaterial_251} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cafe.gltf')
